WebAppZlatarna/Models/Nakit.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebAppZlatarna.Models;

namespace WebAppZlatarna.Models
{
    public class Nakit
    {
        [Required(ErrorMessage = "Polje {0} je obvezno.")]
        [Display(Name = "#")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // iskljucujemo s ovim AUTO_INTCREMENT
        public int Id { get; set; }
        [Required(ErrorMessage = "Polje {0} je obvezno.")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "Polje {0} je obvezno.")]
        [Display(Name = "Datum nabave")]
        [DataType(DataType.Date)]
        public DateTime DatumNabave { get; set; }
        [Required(ErrorMessage = "Polje {0} je obvezno.")]
        [DataType(DataType.Currency)]
        public decimal Cijena { get; set; }
        [Required(ErrorMessage = "Polje {0} je obvezno.")]
        [Display(Name = "Slika")]
        public string SlikaUrl { get; set; }
        [Display(Name = "Kategorija")]
        public int KategorijaId { get; set; }
        // veza - svaki nakit moze imati jednu kategoriju na sebi
        public Kategorija Kategorija { get; set; }
    }
}

WebAppZlatarna/Controllers/NakitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebAppZlatarna.Models;

namespace WebAppZlatarna.Controllers
{
    public class NakitController : Controller
    {
        private readonly IRepozitorijUpita _repozitorijUpita;
        public NakitController(IRepozitorijUpita repozitorijUpita)
        {
            _repozitorijUpita = repozitorijUpita;
        }

        public IActionResult Index()
        {
            return View(_repozitorijUpita.PopisNakit());
        }

        public IActionResult Create()
        {
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv");
            int sljedeciId = _repozitorijUpita.SljedeciId();
            Nakit nakit = new Nakit() { Id = sljedeciId };
            return View(nakit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Naziv,DatumNabave,Cijena,SlikaUrl,KategorijaId")] Nakit nakit)
        {
            ModelState.Remove("Kategorija");//uklanjanje veze

            if (ModelState.IsValid)
            {
                _repozitorijUpita.Create(nakit);
                return RedirectToAction("Index"); // ako je sve ok, tu završava metoda 
            }
            //ako je doslo do greške sljedeci dio se izvrsava
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv", nakit.KategorijaId);
            return View(nakit);

        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }

            Nakit nakit = _repozitorijUpita.DohvatiNakitSIdom(id);

            if (nakit == null) { return NotFound(); }

            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv", nakit.KategorijaId);
            return View(nakit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, [Bind("Id,Naziv,DatumIzlaska,Cijena,SlikaUrl,KategorijaId")] Nakit nakit)
        {
            if (id != nakit.Id)
            {
                return NotFound();
            }

            ModelState.Remove("Kategorija");

            if (ModelState.IsValid)
            {
                _repozitorijUpita.Update(nakit);
                return RedirectToAction("Index");
            }
            //ako je doslo do greške sljedeci dio se izvrsava
            ViewData["KategorijaId"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Id", "Naziv", nakit.KategorijaId);
            return View(nakit);

        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id < 1)
            {
                return NotFound();
            }

            var nakit = _repozitorijUpita.DohvatiNakitSIdom(Convert.ToInt16(id));

            if (nakit == null)
            {
                return NotFound();
            }

            return View(nakit);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var nakit = _repozitorijUpita.DohvatiNakitSIdom(id);
            _repozitorijUpita.Delete(nakit);
            return RedirectToAction("Index");

        }

        //Trazilica
        public ActionResult SearchIndex(string nakitKategorija, string searchString)
        {
            var zanr = new List<string>();

            var kategorijaUpit = _repozitorijUpita.PopisKategorija();

            ViewData["nakitKategorija"] = new SelectList(_repozitorijUpita.PopisKategorija(), "Naziv", "Naziv", kategorijaUpit);

            var nakiti = _repozitorijUpita.PopisNakit();

            if (!String.IsNullOrWhiteSpace(searchString))
            {
                nakiti = nakiti.Where(s => s.Naziv.Contains(searchString, StringComparison.OrdinalIgnoreCase)); // StringComparison.OrdinalIgnoreCase ignorira velika-mala slova 
            }

            if (string.IsNullOrWhiteSpace(nakitKategorija))
                return View(nakiti);
            else
            {
                return View(nakiti.Where(x => x.Kategorija.Naziv == nakitKategorija));
            }

        }


    }
}

WebAppZlatarna/Views/Nakit/Create.cshtml
@model WebAppZlatarna.Models.Nakit

<h4>Nakit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* mozda ne treba START - ovisi*@
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            @* mozda ne treba KRAJ - ovisi*@
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumNabave" class="control-label"></label>
                <input asp-for="DatumNabave" class="form-control" />
                <span asp-validation-for="DatumNabave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cijena" class="control-label"></label>
                <input asp-for="Cijena" class="form-control" />
                <span asp-validation-for="Cijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlikaUrl" class="control-label"></label>
                <input asp-for="SlikaUrl" class="form-control" />
                <span asp-validation-for="SlikaUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KategorijaId" class="control-label"></label>
                <select asp-for="KategorijaId" class="form-control" asp-items="ViewBag.KategorijaId"></select>
                <span asp-validation-for="KategorijaId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-primary" />
            </div>
        </form>

    </div>

</div>

<div>
    <a asp-action="Index">Natrag na popis nakita</a>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }

}

WebAppZlatarna/Views/Nakit/Delete.cshtml
@model WebAppZlatarna.Models.Nakit

<h2> Brisanje nakita: @Model.Naziv</h2>
<h4>Jeste li sigurni u brisanje iznad navedenog nakita?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatumNabave)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatumNabave)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cijena)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kategorija)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kategorija.Naziv)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SlikaUrl)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.SlikaUrl)" width="100" height="100" alt="@Html.DisplayFor(model => model.Naziv)" />
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Obriši" class="btn btn-danger" />
        <a asp-action="Index">Natrag na popis nakita</a>
    </form>
</div>

WebAppZlatarna/Views/Nakit/Index.cshtml
@model IEnumerable<Nakit>

<h1>Popis nakita</h1>
<p>
    <a asp-action="Create" class="btn btn-success"> Unesi novi nakit</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.SlikaUrl)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Id)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Naziv)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.DatumNabave)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Cijena)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Kategorija)</th>
            <th>Radnje nad podacima</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> <img src="@Html.DisplayFor(modelItem => item.SlikaUrl)" width="100" height="100" alt="@Html.DisplayFor(modelItem => item.Naziv)" /> </td>
                <th scope="row">@Html.DisplayFor(modelItem => item.Id)</th>
                <td>@Html.DisplayFor(modelItem => item.Naziv)</td>
                <td>@Html.DisplayFor(modelItem => item.DatumNabave)</td>
                <td>@Html.DisplayFor(modelItem => item.Cijena)</td>
                <td>@Html.DisplayFor(modelItem => item.Kategorija.Naziv)</td>
                <td><a asp-action="Update" asp-route-id="@item.Id" class="btn btn-info"> Uredi</a> | <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Obriši</a></td>
            </tr>
        }
    </tbody>
</table>

WebAppZlatarna/Views/Nakit/SearchIndex.cshtml
@model IEnumerable<Nakit>

<h1>Tražilica nakita</h1>
<p>
    <a asp-action="Create" class="btn btn-success"> Unesi novi nakit</a>
    @using (Html.BeginForm("SearchIndex", "Nakit", FormMethod.Get))
    {
    <p>
        Kategorija: @Html.DropDownList("nakitKategorija", "Sve kategorije")
        Naziv: @Html.TextBox("searchString")

        <input type="submit" value="Traži" class="btn btn-info" />
    </p>
    }
</p>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.SlikaUrl)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Id)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Naziv)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.DatumNabave)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Cijena)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Kategorija)</th>
            <th>Radnje nad podacima</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> <img src="@Html.DisplayFor(modelItem => item.SlikaUrl)" width="100" height="100" alt="@Html.DisplayFor(modelItem => item.Naziv)" /> </td>
                <th scope="row">@Html.DisplayFor(modelItem => item.Id)</th>
                <td>@Html.DisplayFor(modelItem => item.Naziv)</td>
                <td>@Html.DisplayFor(modelItem => item.DatumNabave)</td>
                <td>@Html.DisplayFor(modelItem => item.Cijena)</td>
                <td>@Html.DisplayFor(modelItem => item.Kategorija.Naziv)</td>
                <td><a asp-action="Update" asp-route-id="@item.Id" class="btn btn-info"> Uredi</a> | <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Obriši</a></td>
            </tr>
        }
    </tbody>
</table>

WebAppZlatarna/Views/Nakit/Update.cshtml
@model WebAppZlatarna.Models.Nakit

<h4>Ažuriraj nakit @Model.Naziv</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumNabave" class="control-label"></label>
                <input asp-for="DatumNabave" class="form-control" />
                <span asp-validation-for="DatumNabave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cijena" class="control-label"></label>
                <input asp-for="Cijena" class="form-control" />
                <span asp-validation-for="Cijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlikaUrl" class="control-label"></label>
                <input asp-for="SlikaUrl" class="form-control" />
                <span asp-validation-for="SlikaUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KategorijaId" class="control-label"></label>
                <select asp-for="KategorijaId" class="form-control" asp-items="ViewBag.KategorijaId"></select>
                <span asp-validation-for="KategorijaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Natrag na popis nakita</a>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }

}